### ISSUE TITLE
Lines are rendered with green color

### ISSUE THREAD

**Issue by lunderot** [rikhardsvensson/StortSpel-Grupp1#100]
When running the game at home, all line rendering are green and jagged.
See pictures below

![green electricity](https://cloud.githubusercontent.com/assets/6282953/13329218/effde1ac-dbf2-11e5-8932-4185e7b19651.png)
![green lines](https://cloud.githubusercontent.com/assets/6282953/13329221/f5c1e9c6-dbf2-11e5-8a64-2e63f021380c.png)

**Comment by rikhardsvensson** [comment]
Update drivers and post your specs. Mayhap this is a common alpha blending problem with say, a certain shitty Saphire R9 GPU.

**Comment by lunderot** [comment]
I'm using a ASUS Radeon R9 290. I updated the drivers soon after seeing this in the game, but the problem still persists.

**Comment by ze413X** [comment]
Closed because AMD
