### ISSUE TITLE
Random unplacable tiles in Level Editor

### ISSUE THREAD

**Issue by Texxar** [rikhardsvensson/StortSpel-Grupp1#106]
Sometims random tiles is unplacable for some reason in the Level Editor

**Comment by Zache51** [comment]
Not sure but it might be fixed in b32c6f29dd8b310a1b7397fab3746448a030307f

**Comment by Texxar** [comment]
Have been able to recreate this by moving a placed object to an unavailable position (thus snapping it back to its original pos) and then boxdeleting the object, this will cause that tile to be unplacable

**Comment by SebOnTheWeb** [comment]
Can't replicate. Most likely fixed in 06ef3d7b8681965f8baf85e042cc9f01346c4676
