### ISSUE TITLE
Walk animation bug

### ISSUE THREAD

**Issue by Texxar** [rikhardsvensson/StortSpel-Grupp1#115]
If you tell a guard to move to an unmovable position it will play the first frames of the walk animation but not move anywhere. This looks silly

**Comment by NordicGamer** [comment]
Fixed in 1ec1297d7d23f609aec7d72e4f7d13ad82b695e5

**Comment by NordicGamer** [comment]
In developer c32f355d81953e8249b3be35dd1a6e2df2b5636e
