### ISSUE TITLE
Line aoe overlap with spawn points

### ISSUE THREAD

**Issue by vfarias** [rikhardsvensson/StortSpel-Grupp1#122]
gun traps should have their area stopped by spawn points, the same way they're stopped by walls. As is they become unplaceable if aimed at a spawn point.

**Comment by vfarias** [comment]
Appears to be fixed in 8c4a4a114f29bfd0b529d9889000c4b959da9d66
Needs further testing once trap areas are visible again.

**Comment by Ostus** [comment]
Merged to dev in a771f95f64fb3ab1bcf40868966d0d6fd4770676
