### ISSUE TITLE
Units gets standard rotation in placement state

### ISSUE THREAD

**Issue by SebOnTheWeb** [rikhardsvensson/StortSpel-Grupp1#128]
(Release)
When placing a unit in placement state, it always gets placed in standard direction. It should get the same direction as the ghostimage. Rotation works if you re-select and then rotate again.

**Comment by SebOnTheWeb** [comment]
This also causes the unit to move out of the map if a move command is issued after game is started.

**Comment by Zache51** [comment]
Fixed in 7c2de02e2c451eab93dfc165bea7212842db0e52
