### ISSUE TITLE
Unit walks away when rotated in certain directions

### ISSUE THREAD

**Issue by SebOnTheWeb** [rikhardsvensson/StortSpel-Grupp1#131]
When a unit is placed with a direction towards north-east, south-east, south-west or north-west, it causes the unit to walk north forever. Is caused when you place a unit and its direction is set to north (see other issue) and you start the game and issue a move to the unit.

**Comment by SebOnTheWeb** [comment]
Unit must be moved in (kind of) opposite direction of the direction they're facing.

**Comment by vfarias** [comment]
This seems to have happened because there was an offset done to diagonal cameras which appearently applied to units as well, resulting in a position offset for the movement states.
Should be fixed in be6263bd345940fa1f7c92a6ca176a364a9701be
