### ISSUE TITLE
Lag issues pertaining to the AI and the light culling.

### ISSUE THREAD

**Issue by rikhardsvensson** [rikhardsvensson/StortSpel-Grupp1#135]
The game runs at less than 60 fps on an i7 and a gtx660. The scenario I've run consists of playing the first campaign map with only four guards placed and while fully zoomed in. A rough diagnostic session points in the direction of the functions CheckAllTiles in Unit and GetObjectsInLight in the ObjectHandler.
Will attempt to speed up GetObjectsInLight as CheckAllTiles is already handled by https://github.com/rikhardsvensson/StortSpel-Grupp1/issues/124

**Comment by vfarias** [comment]
CheckedAllTiles is fixed in 21a2963cfe6c6b071329294758e5bdec9c58d834

**Comment by Texxar** [comment]
Analysed and it's not possible to fix lightculling without a major rework of a lot of stuff.
