### ISSUE TITLE
Particles are rendered twice

### ISSUE THREAD

**Issue by lunderot** [rikhardsvensson/StortSpel-Grupp1#148]
![particles twice](https://cloud.githubusercontent.com/assets/6282953/13631255/ff87e186-e5e3-11e5-81bf-33f12b4be3ab.png)
As you can see, the particles are rendered over the guards and over the grass. Offset seems to be the same for all of them.

**Comment by vfarias** [comment]
This is the same issue as  #144

**Comment by Texxar** [comment]
Fixed in a1caaf7b11c23f007927e6c9a5afef5c4ef834b9
