### ISSUE TITLE
Apply options button resets

### ISSUE THREAD

**Issue by vfarias** [rikhardsvensson/StortSpel-Grupp1#149]
After applying options, clicking anywhere, besides where the apply-button usually is, will cause the button to reappear.

**Comment by rikhardsvensson** [comment]
Fixed in a054c838a85934211e727e48c4e89382f51df1c1.
Could someone test this and report if it works properly.
I will merge with dev when the issue has been closed.

**Comment by SebOnTheWeb** [comment]
I WILL TRY TO FUCK SOMETHING UP!

**Comment by SebOnTheWeb** [comment]
HAHAHA! f55ee40c5124a5a1c92d1682c524c63207a116fd
PS. I SUCK DONKEY BALLS!
