### ISSUE TITLE
Placement on spawn

### ISSUE THREAD

**Issue by vfarias** [rikhardsvensson/StortSpel-Grupp1#150]
Guards, enemies, loot, and furniture can be placed on spawnpoints. In the case of guards, it applies to both placement mode and the level editor.

**Comment by SebOnTheWeb** [comment]
Can be fixed with no placement zones and good level design.

**Comment by vfarias** [comment]
Or it could be actually fixed.

**Comment by vfarias** [comment]
Fixed in 4a458e6dbb604629b14654c91676bb2313bf2b82
Merged into dev in 86ee2f5774806ff152cb8be9a8a796c3c9956478
