### ISSUE TITLE
Machiene gun muzzle flash is bugged

### ISSUE THREAD

**Issue by SebOnTheWeb** [rikhardsvensson/StortSpel-Grupp1#153]
(Release)
It is displayed in the upper right corner when gun activates.

**Comment by Texxar** [comment]
Fixed in 9179dcea382a6491dfcbd90ec1fff4c0b8e7d21a

**Comment by ze413X** [comment]
Other traps suffer from this issue as well. The error is inside the model format.

**Comment by Texxar** [comment]
Fixed in 8e09b12836aac7b382c2db7d4bdf94b684cfda89
