### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Ostus** [rikhardsvensson/StortSpel-Grupp1#154]
I play in skirmish.
First I play Honorary Defence, don't place any Guards.
Secondly I play lotus, place a Guard at each Loot-gathering.
Thirdly I play peerlevel.
Then I exit the game from the Main Menu and get 42 memory leaks

**Comment by vfarias** [comment]
FIXED in 63b4bc5f403e5f071e07a9ac813a691d0541367f
