### ISSUE TITLE
Drag box selection has offset in lower resolutions

### ISSUE THREAD

**Issue by konglobemeralt** [rikhardsvensson/StortSpel-Grupp1#163]
Only visual

**Comment by julietbox** [comment]
Checks if fullscreen is active. If active take window resolution and not screen resolution.
372aee197a3102f5bdc6b8ab9a2d60df72492fe5

**Comment by julietbox** [comment]
Sorry don't work yet.

**Comment by julietbox** [comment]
Now it works 4901c52f97e447f9602effe8161962e677e37ed4
