### ISSUE TITLE
Game crash when placing camera on this location (see picture)

### ISSUE THREAD

**Issue by julietbox** [rikhardsvensson/StortSpel-Grupp1#164]
![image](https://cloud.githubusercontent.com/assets/10449040/13704205/faa8a052-e79a-11e5-87ae-3e0a2fdc8c8e.png)

**Comment by julietbox** [comment]
Fixed in de5d9af3559f615bf8aca22421cbc155af40ac8c

**Comment by SebOnTheWeb** [comment]
Crashes again when replacing the same camera.

**Comment by vfarias** [comment]
Should work now.
