### ISSUE TITLE
Objecthandler tries to add the same item twice

### ISSUE THREAD

**Issue by vfarias** [rikhardsvensson/StortSpel-Grupp1#21]
When adding objects, add() gets called twice. This doesn't actually break the game, since the second object gets immediately removed due to the first object already occupying the space. Nevertheless it seems unnecessary.

**Comment by Zache51** [comment]
Probably solved because BaseEdit now keeps the ghost object so only one object is created when something is placed. Before the ghostobject was recreated at the same time.
