### ISSUE TITLE
Re-organize files into seperate folders

### ISSUE THREAD

**Issue by Zache51** [rikhardsvensson/StortSpel-Grupp1#25]
EDIT1:
Perhaps a seperate folder for game objects and others in a utility folder perhaps.

**Comment by jeen13** [comment]
What files? Where?

**Comment by Zache51** [comment]
The topic should be refrased so I will do that.

Game object classes should be in their seperate folder because it´s a little messy right now. It was changed but the commit was later reverted and this issue was forgotten.

**Comment by rikhardsvensson** [comment]
Fixed in 5a406087ca2a135d2320d57e7d948e3a413d574c. Pending evaluation before moving it into dev.
