### ISSUE TITLE
Crazy guards

### ISSUE THREAD

**Issue by Texxar** [rikhardsvensson/StortSpel-Grupp1#37]
Guards sometimes gets stuck on a tile and can be quite easily be made to walk through walls

**Comment by vfarias** [comment]
Walking through walls is mainly caused by a rounding error due to being in between tile positions. I will have a look at is as part of the AI restructuring planned for next week

**Comment by Texxar** [comment]
Seems to be fixed, even I have not been able to make guards walk through walls or get them stuck.
