### ISSUE TITLE
Ram memory too high

### ISSUE THREAD

**Issue by ze413X** [rikhardsvensson/StortSpel-Grupp1#46]
We are at 333mb RAM. Like 1-2 weeks ago, this was around 30-40mb. Something is wrong.

**Comment by ze413X** [comment]
GetTexture does not handle properly. If I for example do; GetTexture("floor.png"); in games update loop. RAM will increase for each loop. Same thing happens when the menus are loaded in. For each UI element, the RAM increases because of it.

**Comment by SebOnTheWeb** [comment]
SoundModule is the culpit.

**Comment by SebOnTheWeb** [comment]
FIXED in f0a41286013647c8d5b498210d0027d8618df42e. Saved 160~ MB by streaming the music.
