### ISSUE TITLE
Walking into walls

### ISSUE THREAD

**Issue by ze413X** [rikhardsvensson/StortSpel-Grupp1#58]
This is a known issue that have been there for a while. Someone should sit down and actually resolve it.

**Comment by vfarias** [comment]
Fixed in [T4-17-AI-Cleanup](https://github.com/rikhardsvensson/StortSpel-Grupp1/tree/T4-17-AI-Cleanup)

**Comment by vfarias** [comment]
Err.. nevermind. There's a different wall walking issue now.

**Comment by vfarias** [comment]
Hopefully fixed for good in c71f475
