### ISSUE TITLE
Assetmanager - Memory leak inside Scantexture

### ISSUE THREAD

**Issue by ze413X** [rikhardsvensson/StortSpel-Grupp1#6]
Inside ScanTexture, we get a memoryleak caused by something in these lines:

```
Texture* texture = new Texture;
texture->_filename = wstring(filename.begin(), filename.end());
_textures->push_back(texture);
return texture;
```

**Comment by FredrikLindsten** [comment]
While this showed a case where textures would not be deleted, the real issue is that we have two AssetManagers.

UIHandler and ObjectHandler will need to share.
