### ISSUE TITLE
Unclear objects - Diamond should be lit up

### ISSUE THREAD

**Issue by ze413X** [rikhardsvensson/StortSpel-Grupp1#61]
This issue is not necessarily specific to the diamond but could be objects in general. One of the specific issues was that the diamond should be on a pedistal and lit up. Which sounds good. So the player gets more indication of the purpose and the goal.

**Comment by NordicGamer** [comment]
The diamond are lit up in branch T5-17-Animate-Objects.

**Comment by NordicGamer** [comment]
Now the diamonds are lit up and the light follows the diamond but turns off when thief are hiding. Implemented in developer. The pedistal are in the levels but are waiting to be loaded until everyone have merged with the developer.
