### ISSUE TITLE
Description of objects

### ISSUE THREAD

**Issue by ze413X** [rikhardsvensson/StortSpel-Grupp1#62]
Should be read from a string from blueprints inside objecthandler.

**Comment by Zache51** [comment]
I think it´s now possible to add descriptions of objects in a JSON file and somewhere else in the code.

**Comment by SebOnTheWeb** [comment]
Kind of fixed with popups when hovering over a trap.

**Comment by SebOnTheWeb** [comment]
Done in 17aa93942a9cbe21776f788d8fc80ea29e80461d
