### ISSUE TITLE
You won screen to easy to click away

### ISSUE THREAD

**Issue by ze413X** [rikhardsvensson/StortSpel-Grupp1#64]
People had trouble determining whether or not they won or lost if he/she clicked a lot.

**Comment by NordicGamer** [comment]
Now win or lose screen shows 3 seconds and then it can be clicked on with a smaller button.

6c915ef77f07ed67892a8af5553b0eedbd429a5a

**Comment by NordicGamer** [comment]
Now pushed to developer.

5caf573613a62c00f80d027015a6db3c0c082de2

**Comment by NordicGamer** [comment]
Now pushed to developer.

5caf573613a62c00f80d027015a6db3c0c082de2
