### ISSUE TITLE
Text input should have a blinking cursor

### ISSUE THREAD

**Issue by ze413X** [rikhardsvensson/StortSpel-Grupp1#68]
This should be updated with delta time.

**Comment by ze413X** [comment]
Resolved in 0d45de7d8af2b891afbfcd02bf4ec86581a6dbba

**Comment by lunderot** [comment]
This isn't solved in 0d45de7d8af2b891afbfcd02bf4ec86581a6dbba

**Comment by rikhardsvensson** [comment]
Solved in 2c685865d23cf2fbad970a187a5536de6cb322dd
