### ISSUE TITLE
Game close upon final guard death (tesla traps involved)

### ISSUE THREAD

**Issue by julietbox** [rikhardsvensson/StortSpel-Grupp1#72]
In Developer 0d45de7d8af2b891afbfcd02bf4ec86581a6dbba
When the last guard is killed AFTER a tesla trap has been activated, game closed unexpectedly.

Played on Best in the Business with 2 guards, 2 teslas and 1 camera like so:
![issue](https://cloud.githubusercontent.com/assets/10449040/13110981/81ea9108-d583-11e5-87a0-ae5be4c0267f.png)
Let lower guard be defeated, then wait for rightmost tesla to be activated and let higher guard be defeated. This has been recreated 3 times (ask Julia if needed).

**Comment by Texxar** [comment]
Might have been solved in a similar bugfix  e8566375124a2f32ac9c907b6fc399de866fd22e
