### ISSUE TITLE
Majority of all buttons have a offset with negative Y, picking issue?

### ISSUE THREAD

**Issue by jeen13** [rikhardsvensson/StortSpel-Grupp1#84]
Noticed that almost all buttons cannot be selected by pressing at either half top of their button or at 1/3 of the top of the button. An example will be shown by the picture below:

![button offset](https://cloud.githubusercontent.com/assets/10449042/13172988/5535f534-d6fb-11e5-9f42-626a68d30ef4.png)

This was first noticed in the level editor's radio buttons where they had an offset of half the buttons, then I decided to try it out in both Level Foundation and Developer and discovered that this issue is there as well.

Is this a picking issue? Has it to do with the tile offset issue?

**Comment by Texxar** [comment]
Seems to be a similar issue with tilepicking, I will look into it

**Comment by lunderot** [comment]
Seems to be an issue only when resolution is 1080p and a issue with window

**Comment by Texxar** [comment]
Fixed in 2da16e93be4c2e3d69567a0fd0cef8b6c70ba629
