### ISSUE TITLE
Game crashes when leaving Level Edit

### ISSUE THREAD

**Issue by jeen13** [rikhardsvensson/StortSpel-Grupp1#87]
Program crashes on delete marker when trying to return to menu while in painting mode in the level editor.

In Level Foundation Branch!

**Comment by jeen13** [comment]
In Level Foundation Branch!

**Comment by Zache51** [comment]
Does it crash in the ReleaseMarkers() function in BaseEdit?

**Comment by Zache51** [comment]
28be5331a3aec20679528b5a64029c68b52daf44
