### ISSUE TITLE
Clearer box selecting

### ISSUE THREAD

**Issue by Texxar** [rikhardsvensson/StortSpel-Grupp1#88]
Box selecting units should be indicated by drawing a box in viewspace of the area that is about to be selected

**Comment by NordicGamer** [comment]
Fixed in 0f2e22709d8089999dabe43c7c43204ec9c73505
However if going in tutorial then this needs to be handled correctly.

**Comment by lunderot** [comment]
Fixed in 51d4a5488679e4d83698401f21d89e55703799fb
