### ISSUE TITLE
Can't set volume in optionsstate

### ISSUE THREAD

**Issue by lunderot** [rikhardsvensson/StortSpel-Grupp1#89]
The volume buttons simply are not implemented

**Comment by NordicGamer** [comment]
I'm working on it.

**Comment by NordicGamer** [comment]
Implemented in I89-Sound-Option and can now set volume depending on channel.
Exampel: _soundModule->SetVolume((_soundOption + 1.0f) / 10.0f, CHMASTER);

**Comment by lunderot** [comment]
Fixed in 4e7689518a8b0da674aa8ce4ee416273d6e98c23
